### ISSUE TITLE
media

### ISSUE THREAD

**Issue by dchinmay2** [p00f/godbolt.nvim#1]

**Comment by p00f** [comment]
https://user-images.githubusercontent.com/36493671/142676167-488e23a6-c52a-4bd8-8f5b-c00f55632105.mp4

**Comment by p00f** [comment]
async:

https://user-images.githubusercontent.com/36493671/142684304-68e606a2-faa5-4aa1-ab16-09f509f661ce.mp4

**Comment by p00f** [comment]
highlight on cursormoved instead of cursorhold

https://user-images.githubusercontent.com/36493671/142686106-4826765d-28cf-4fd8-b8bb-87ed284ae85e.mp4

**Comment by p00f** [comment]
with compiler flags:

https://user-images.githubusercontent.com/36493671/142724037-5a9127d0-88e2-461e-a525-de83664c8166.mp4

**Comment by dchinmay2** [comment]
https://user-images.githubusercontent.com/36493671/142733190-433f8057-6be2-4012-a235-435f30c8a012.mp4

**Comment by dchinmay2** [comment]
choosing compiler using fuzzy finders:



https://user-images.githubusercontent.com/36493671/142774015-9fb20d17-fef0-497a-87dd-ed0f52e8bec4.mp4

**Comment by dchinmay2** [comment]
updated video: prompt for flags

https://user-images.githubusercontent.com/36493671/143026157-d74eaa39-6768-4f7a-8e36-f5395464c3ec.mp4

**Comment by p00f** [comment]
logo:
![godbolt-nvim](https://user-images.githubusercontent.com/36493671/143468340-cb8ad902-87bc-47b0-8521-9790496db694.png)

**Comment by dchinmay2** [comment]
logo

![godbolt-nvim-small](https://user-images.githubusercontent.com/36493671/143468676-089f623f-f913-4af6-bc78-dbfaa1e92c69.png)
