### ISSUE TITLE
open compiler output in split

### ISSUE THREAD

**Issue by dchinmay2** [p00f/godbolt.nvim#10]
Currently I only print stdout and stderr of the compiled program to `:messages`

godbolt.org has an option to display compiler output, my idea is to:

if `b:godbolt_exec` is false:
-> open a split only if the compiler outputs something

if `b:godbolt_exec` is true:
-> open a split if the compiler outputs something and add the program output to the same split. if the compiler doesnt output anything then open a new split for program output

does this look good @ii14 @darzok0914 ?

**Comment by ii14** [comment]
Why not use a quickfix/loclist for this? Don't open any splits by default, and if the compilation fails, a simple, one-line message could be reported with `:echo` or `vim.notify`. And then you could open the split with errors with `:lopen`. You can also get error messages from GCC parsed for basically free, as vim already can do that out of the box.

**Comment by dchinmay2** [comment]
another user has said they want warnings too. I don't want to special-case gcc and quickfix is useless if it doesnt parse output

Or maybe I should special-case things like gcc and clang

**Comment by mellery451** [comment]
I think warnings as well as errors are fine for going to quickfix/loclist...I think they should parse similarly (errfmt). I'd be fine with a split for the program output though (in cases where execution is enabled).

**Comment by dchinmay2** [comment]
Understood, thanks

**Comment by ii14** [comment]
Maybe I wasn't clear, the output can be always fed to loclist, the user will just have to open the loclist window manually.

See `:echo readdir($VIMRUNTIME.'/compiler')` for what compilers are supported out of the box. If all else fails, you can just set the generic `FILE:LINE:COL` parsing.

**Comment by dchinmay2** [comment]
Ah ok. Thanks for your input, I'll take some time to implement this as I have evals coming up

**Comment by ii14** [comment]
> I'd be fine with a split for the program output though (in cases where execution is enabled).

Can't the program output also go to loclist?

**Comment by mellery451** [comment]
both LL and QF imply a buffer location (line/col) that can be jumped to. warnings and errors certainly fit that description...program output not so much. That said, sending stdout sent to LL instead of messages would still be an improvement.

**Comment by dchinmay2** [comment]
4eb69016d620711ebab85acdf6d2e881e7139f24 adds the compiler-stderr-in-quickfix feature (with working line and column numbers)

See the readme for details (https://github.com/p00f/godbolt.nvim#Setup and https://github.com/p00f/godbolt.nvim#quickfix)

**Comment by dchinmay2** [comment]
Can this be closed?

**Comment by mellery451** [comment]
works great - thanks

**Comment by dchinmay2** [comment]
after a0edd27ab0dc04042a50eca6371f93eb5b285bce program output also opens in a split (with exit code, stdout and stderr)
