### ISSUE TITLE
Feature Request: full display of compilation errors and warnings

### ISSUE THREAD

**Issue by mellery451** [p00f/godbolt.nvim#11]
I often use godbolt to enable a bunch of diagnostics for code (e.g. -Wall -Wextra -Wpedantic) to make sure a snippet is really warning clean. It would be great to have the option for a second window that has all the compiler output, including cases where compilation fails with an error. 

I'm not experienced with lua/plugin development, but I'd be willing to help implement such a feature if you could suggest a starting point or implementation outline.

Thanks.

**Comment by dchinmay2** [comment]
does #10 look good?

**Comment by dchinmay2** [comment]
closed in favour of #10
