### ISSUE TITLE
Make `godbolt_exec` part of the lua config struct

### ISSUE THREAD

**Issue by sbmueller** [p00f/godbolt.nvim#19]
Right now configuration of this plugin takes place in the lua config struct and additionally the vim variable `godbolt_exec`. It would be nice if all configuration could take place in the lua config struct:
```lua
require("godbolt").setup({
    languages = {
        cpp = { compiler = "g122", options = {} },
        c = { compiler = "cg122", options = {} },
        rust = { compiler = "r1650", options = {} },
        -- any_additional_filetype = { compiler = ..., options = ... },
    },
    quickfix = {
        enable = false, -- whether to populate the quickfix list in case of errors
        auto_open = false -- whether to open the quickfix list in case of errors
    },
    url = "https://godbolt.org", -- can be changed to a different godbolt instance
    execute = false -- change to true if code shall be executed as well
})
```

**Comment by dchinmay2** [comment]
Pasting from #18 :

> I thought people don't always want to execute their code.
> It might not even be executable all the time, like when there is no main in the current buffer

**Comment by sbmueller** [comment]
Yes sure, but the default can still be `false` right? So the behavior is the same as with `godbolt_exec`, only the location of that setting is changed.

**Comment by dchinmay2** [comment]
If you do that then you'll have to edit your config every time you want to execute

**Comment by sbmueller** [comment]
Yes you're right, since `godbolt_exec` is buffer-local.
Then I think for the most generic use-case, it is fine as it is.
