### ISSUE TITLE
Change direction of window split

### ISSUE THREAD

**Issue by rmenai** [p00f/godbolt.nvim#29]
It would be nice to be able to split the window on the right when running the GodBolt command.

**Comment by dchinmay2** [comment]
you can make a wrapper that sets [`'splitright'`](https://neovim.io/doc/user/options.html#'splitright'), calls godbolt, then unsets it

i'm surprised most people don't have splitright always set

**Comment by dchinmay2** [comment]
closing unless there's more demand for this
