### ISSUE TITLE
Better Setup Instructions With Example

### ISSUE THREAD

**Issue by pbotmeyertron** [p00f/godbolt.nvim#4]
This plugin looks really great and I think will be used by many people, but the setup instructions are a bit lacking. Can you provide a bit more detail on how you get things working with the plugin? Are there dependencies other than Neovim .6? The setup instructions provided, do they go directly into the init.vim file or somewhere else? Please provide an actual example of how you get this setup and working.

**Comment by dchinmay2** [comment]
The only other dependency is curl. The snippet goes into a lua block like
```
lua << EOF
    snippet_here
EOF
```
if your config is in vimscript and directly if it is in lua

I'll fix the readme and add vimdoc soon, thanks for reporting!

**Comment by dchinmay2** [comment]
Does the readme look fine now?
