### ISSUE TITLE
Have compiler output

### ISSUE THREAD

**Issue by darzok0914** [p00f/godbolt.nvim#5]
Hi, I just found your plugin and I was wondering if you had planned to add a compiler output feature. Sometimes, we don't necessarily have a compiler installed locally and it can be nice. Also is it possible to use a code that uses 3rd party libraries like boost? On godbolt we can add these as options, how does it work with this plugin ?

**Comment by dchinmay2** [comment]
I don't understand your first request, could you be more clear? I'll add the libraries feature

**Comment by darzok0914** [comment]
For example on godbolt we can either have the assembly output of our program or just run it so for instance if you have std::cout << "hello\n" you would see : 
---------
Hello

**Comment by dchinmay2** [comment]
I see

**Comment by dchinmay2** [comment]
I updated the setup, it should now work with boost. See the readme for details

**Comment by dchinmay2** [comment]
fixed by https://github.com/p00f/godbolt.nvim/commit/e416f48de30b1ee328f62389787e3110b2ba1632

**Comment by dchinmay2** [comment]
If you `:let b:godbolt_exec = v:true` in a buffer, subsequent calls will echo the output/error to the message area

**Comment by mellery451** [comment]
I tried this option and get the error:

```
E5108: Error executing lua ...mellery/.vim/bundle/godbolt.nvim/lua/godbolt/execute.lua:30: attempt to call a string value
stack traceback:
        ...mellery/.vim/bundle/godbolt.nvim/lua/godbolt/execute.lua:30: in function 'godbolt'
        [string ":lua"]:1: in main chunk
```

..did I do something wrong?

**Comment by dchinmay2** [comment]
did you use a custom compiler? if yes, which one? please also paste the source code

**Comment by dchinmay2** [comment]
nevermind i can reporduce it

**Comment by dchinmay2** [comment]
fixed (extra pair of brackets)

**Comment by mellery451** [comment]
working now  - thanks!
