### ISSUE TITLE
[feature request] Autoscroll

### ISSUE THREAD

**Issue by mcauley-penney** [p00f/godbolt.nvim#6]
Thanks for this plugin and awesome work!

A feature that I'd love with this is autoscroll. For example, as you scroll through your source code, the split that displays the corresponding assembly scrolls with you. 

Thanks for your time!

**Comment by dchinmay2** [comment]
I don't have a clear idea rn, I'll think about this after I implement the TODOs mentioned in the readme

**Comment by darzok0914** [comment]
That’s actually a good idea for an extension. TSPlayground works like this, I wonder how they do but typically something similar would be a killer feature.

**Comment by krady21** [comment]
Shameless plug, but I have impemented a similar feature for my plugin: https://github.com/krady21/compiler-explorer.nvim. It is based on `vim.api.nvim_win_set_cursor`.

**Comment by dchinmay2** [comment]
What do you do when one line of source code corresponds to more than a page of assembly?

**Comment by krady21** [comment]
I always set the cursor to the first line from the corresponding assembly output. I also thought about setting the cursor to the line exactly in the middle of the assembly output, but ended up going with the first option.

**Comment by dchinmay2** [comment]
@krady21 then if the user jumps to the assembly window to scroll (because it doesn't fit etc) and then jumps back to the source window, it will count as a `CursorMoved` and the assembly window will scroll back up again right?

This is a hard problem, I think this is why godbolt.org doesn't do it either

**Comment by dchinmay2** [comment]
I'm closing this as it seems impossible to solve due to the window-jumping issue mentioned in the previous comment - I tried out compiler-explorer.nvim which has the same issue
