### ISSUE TITLE
errors in decode..

### ISSUE THREAD

**Issue by mellery451** [p00f/godbolt.nvim#9]
I seem to get this for quite a few buffers:

```
^I...ellery/.vim/bundle/godbolt.nvim/lua/godbolt/assembly.lua:76: in function <...ellery/.vim/bundle/godbolt.nvim/lua/godbolt/assembly.lua:75> function: builtin#18 ...ellery/.vim/bundle/godbolt.nvim/lua/godbolt/assembly.lua:76: Expected v
alue but found invalid token at character 1
stack traceback:
^I[C]: in function 'decode'
^I...ellery/.vim/bundle/godbolt.nvim/lua/godbolt/assembly.lua:76: in function <...ellery/.vim/bundle/godbolt.nvim/lua/godbolt/assembly.lua:75>
```

Here's a buffer that produces such an error for me:
```
#include <cstdio>
#include <iostream>
#include <string>
//#include <cstring>

void rev_chars(char * pstart, char * pend)
{
    char tmp;
    while (pstart < pend) {
        tmp = *pstart;
        *pstart = *pend;
        *pend = tmp;
        pstart += 1;
        pend -= 1;
    }
}

int main(int argc, char * argv[]) {
    std::string sentence(argv[1]);
    char * buffer = new char[sentence.size() + 1];
    strncpy(buffer, sentence.c_str(), sentence.size());
    // first, rev the whole string
    rev_chars(buffer, buffer + sentence.size() - 1);

    // now rev each word
    char * pstart = buffer;
    char * pend = buffer;
    char * string_end = pstart + sentence.size();
    while (pend < string_end) {
        if (*pend == ' ') {
            rev_chars(pstart, pend-1);
            pstart = pend + 1;
        }
        pend += 1;
    }
    rev_chars(pstart, pend-1);

    std::cout << buffer << std::endl;
}
```

**Comment by dchinmay2** [comment]
not sure, the response is "unexpected end of json input" but i checked what i post, it is indeed valid json i think

https://paste.rs/p3m.json

**Comment by dchinmay2** [comment]
found the bug, when you compare *pend to space the single quotes end these single quotes 

https://github.com/p00f/godbolt.nvim/blob/38f36227e0839725aedd10d979e857f0400ea1c4/fnl/godbolt/init.fnl#L45


which completely messes up the request

**Comment by dchinmay2** [comment]
> I seem to get this for quite a few buffers:

Just to confirm, you don't get this for any buffer which doesn't have single quotes right?

**Comment by mellery451** [comment]
It hadn't occurred to me that single quotes was the common factor in the problematic buffers, but I suspect you are correct...quick spot-check of a few that were causing problem is consistent with that theory. thanks.

**Comment by mellery451** [comment]
hmmm...I still get the same error with 03218b8. Does my original example work for you with the latest changes?

**Comment by dchinmay2** [comment]
the escaping seems to depend on shell

**Comment by dchinmay2** [comment]
I think I'll have to depend on https://github.com/Lua-cURL/Lua-cURLv3 to do this in a cross-shell way

**Comment by dchinmay2** [comment]
> the escaping seems to depend on shell

or not

**Comment by dchinmay2** [comment]
I could create a temporary JSON file and use that instead, it will work on all shells

**Comment by dchinmay2** [comment]
can you see if e675fd8 works?

**Comment by dchinmay2** [comment]
This should be robust, converting the text to json is handled by neovim

**Comment by mellery451** [comment]
seems to work...thanks
